const WHITE_COLOR = '#ffffff';
const GREY_COLOR = '#8C9499';
const LIGHT_GREY_COLOR = '#D6DEE4';
const BLACK_COLOR = '#000000';
const LIGHT_GRAY = '#F4F5F6';
const ALICE_BLUE = '#ECF0F3';
const REGENT_GRAY = '#979FA3';
const SHUTTLE_GRAY = '#586268';
const PATTENS_BLUE = '#DBE2E8';
const SPINDLE = '#BCC6CC';

export default {
  // DefaultBlue : '#0C529B',
  DefaultBlue:'#47e4c2',
  defaultBackground: WHITE_COLOR,
  defaultBorder: LIGHT_GREY_COLOR,
  locateMeButtonBg: '#f5f5f5',
  font: '#464F55',
  lightFont: '#6C767D',
  greyFont: GREY_COLOR,
  fieldLabelColor: GREY_COLOR,
  buttonDisabledBgColor: ALICE_BLUE,
  titleColor: SHUTTLE_GRAY,
  inputTextColor: SHUTTLE_GRAY,
  buttonTextColor: WHITE_COLOR,
  buttonDisabledTextColor: '#8c9396',
  subButtonTextColor: '#e37439',
  fieldDescriptionText: '#8c9396',
  screenTitleColor: '#5a6166',
  modeSwitcherText: '#eb9142',
  fieldMarkerBgColor: LIGHT_GREY_COLOR,
  fieldMarkerTextColor: '#6C767D',
  buttonGradientLeftColor: '#F26F21',
  buttonGradientRightColor: '#FFB521',
  verticalArrow: LIGHT_GREY_COLOR,
  errorTextColor: '#ff0000',
  borderImageColor: SPINDLE,
  inputHint: '#798187',
  fnnOrange: '#F26F21',
  // fnnOrange: '#00DF88',
  ordersBackground: LIGHT_GRAY,
  helpBackground: LIGHT_GRAY,
  startTagGradientLeftColor: '#F26F21',
  startTagGradientRightColor: '#FAA845',
  emphasizedEndTag: '#E85964',
  cardShadowColor: 'rgb(159,183,200)',
  whiteTagTextColor: WHITE_COLOR,
  autocompleteModal: {
    bgColor: WHITE_COLOR,
    headerBorderColor: LIGHT_GREY_COLOR,
    searchBorderColor: '#8c9396',
    itemTextColor: '#6d757a',
    clearIconColor: '#91989c',
  },
  profileAddPhotoBackground: SPINDLE,
  doneIconBg: '#47D087',
  activeIconBg: GREY_COLOR,
  supplierTitleColor: GREY_COLOR,
  editScreenButton: GREY_COLOR,
  editScreenTitleColor: GREY_COLOR,
  editScreenButtonDisabled: LIGHT_GREY_COLOR,
  orderDetailsSectionBg: WHITE_COLOR,
  orderDetailsTitleExpandedBg: LIGHT_GRAY,
  smallOrderButtonBorderColor: '#a7acb0',
  smallOrderButtonTextColor: '#a7acb0',
  smallOrderButtonBgColor: WHITE_COLOR,
  productItemBaseColor: '#ebeef0',
  productItemTextColor: '#5a6063',
  subButtonBorderColorDisabled: '#d8dee3',
  subButtonBorderColor: '#F26F21',
  activeTabLabelColor: '#F26F21',
  completeProductIconColor: '#6ecc8c',
  editProductsTabIconBg: ALICE_BLUE,
  errorsCountTagColor: '#E85964',
  errorsCountTextColor: WHITE_COLOR,
  notificationIcon: GREY_COLOR,
  requestedProductRowColor: LIGHT_GRAY,
  requestedProductTextColor: '#424B50',
  activateButton: {
    active: '#51D692',
    inactive: '#778188',
  },
  offlineIndicatorBackground: '#767F84',
  orderUpdatedBlock: '#FDF5E4',
  commentItemBorder: LIGHT_GREY_COLOR,
  commentAuthorColor: '#424B50',
  commentMainText: SHUTTLE_GRAY,
  inputMultilineBorder: '#6C767D',
  symbolsCounter: GREY_COLOR,
  imageBackDrop: BLACK_COLOR,
  filePreviewBg: LIGHT_GRAY,
  warningColor: '#E85964',
  tabColor: '#6D757A',
  orderCardBorder: LIGHT_GREY_COLOR,
  deadlineTagBg: '#6C767D',
  moreTagBorder: '#C3CDD2',
  moreTagText: '#778188',
  iosStatusBar: '#6D757A',
  notificationBorder: PATTENS_BLUE,
  notificationDate: '#778188',
  readNotificationBackground: LIGHT_GRAY,
  hasUnread: '#F78F26',
  payItemsScreenBackground: ALICE_BLUE,
  checkoutButton: '#F89A2A',
  checkoutButtonDisabled: REGENT_GRAY,
  checkoutScreenMainText: SHUTTLE_GRAY,
  helpText: '#626d73',
  email: '#f47b25',
  cameraCloseButtonText: WHITE_COLOR,
  cameraControlsBg: '#00000095',
  tankBlockBorder: PATTENS_BLUE,
  imageActivityIndicator: '#131618',
  orderSummaryItemBaseColor: REGENT_GRAY,
  orderSummaryItemTextColor: WHITE_COLOR,
  orderSummaryItemNameTextColor: SHUTTLE_GRAY,
  orderSummaryItemStatusTextColor: SPINDLE,
};
